<%@ Page Title="BMLMedico" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="BMLMedico.aspx.cs" Inherits="TPI_GRUPO_25.BMLMedico" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        body {
            background-color: #ffe5b4;
            margin: 0;
            padding: 0;
        }

        .navbar {
            background-color: #653208 !important;
        }

        .navbar .nav-link,
        .navbar .navbar-brand {
            color: #fce7c6;
            font-weight: 400;
        }

        .badge-personalizada {
            background-color: #9E5439;
            padding: 30px;
            font-weight: bold;
        }
    </style>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="bg-naranja-suave w-100">
               <nav class="navbar navbar-expand-xl" CssClass="navbar" style="background-color: #653208;">
  <div class="container-fluid" >
    <a class="navbar-brand" href="SesionIniciadaAdministrador.aspx">Clínica TUP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDark" aria-controls="navbarDark" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse show">
      <ul class="navbar-nav me-auto mb-2 mb-xl-0 d-flex w-100">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="AltaMedico.aspx">Alta Médico</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="AltaPaciente.aspx">Alta Paciente</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="BMLPaciente.aspx">BML Paciente</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="InformesAdministrador.aspx">Informes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="TurnosAdministrador.aspx">Turnos</a>
        </li>
            <li class="nav-item ms-auto">
              <asp:Label class="nav-link mb-15" runat="server" Text="Usuario: Admin"></asp:Label>
            </li>
        <li class="nav-item">
<a class="nav-link btn btn-primary"  href="InicioSesion.aspx">Cerrar Sesión</a>

        </li>
      </ul>
    </div>
  </div>
</nav>
    </div>
    <asp:Label runat="server" ID="lblBienvenida" Text="Bienvenido Administrador: Aquí se hace la baja, modificación y lectura de médicos" CssClass="h2 text-center d-block mt-5 mb-3 text-dark"></asp:Label>
  <div class="container my-6 pt-5">
<asp:GridView ID="gvMedicos" runat="server" AllowPaging="true" AutoGenerateColumns="false" CssClass="grid-style" Width="100%" PageSize="5" PagerStyle-HorizontalAlign="Center" PagerStyle-Font-Size="Large" HorizontalAlign="Center" CellPadding="3" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="2px" CellSpacing="2" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="gvMedicos_RowDeleting" DataKeyNames="Legajo" OnRowCancelingEdit="gvMedicos_RowCancelingEdit" OnRowEditing="gvMedicos_RowEditing" OnRowUpdating="gvMedicos_RowUpdating" OnPageIndexChanging="gvMedicos_OnPageIndexChanging">
    <Columns>
        <asp:TemplateField HeaderText="Usuario">
            <EditItemTemplate>
                <asp:TextBox ID="txtEditUsuario" runat="server" Text='<%# Bind("Usuario") %>'></asp:TextBox>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="lblUsuario" runat="server" Text='<%# Bind("Usuario") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Contraseña">
            <EditItemTemplate>
                <asp:TextBox ID="txtEditContraseña" runat="server" Text='<%# Bind("Contraseña") %>'></asp:TextBox>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="lblContraseña" runat="server" Text='<%# Bind("Contraseña") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Especialidad">
            <EditItemTemplate>
                <asp:DropDownList AutoPostBack="True" ID="ddlEditEspecialidad" runat="server" DataSourceID="SqlDataSource1" DataTextField="nombre_E" DataValueField="codEspecialidad_E">
                </asp:DropDownList>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:clinicaTUPConnectionString %>" SelectCommand="SELECT [codEspecialidad_E], [nombre_E] FROM [ESPECIALIDADES]"></asp:SqlDataSource>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="Label1" runat="server" Text='<%# Bind("Especialidad") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Legajo">
            <EditItemTemplate>
                <asp:Label ID="lblEditLegajo" runat="server" Text='<%# Bind("Legajo") %>'></asp:Label>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="lblLegajo" runat="server" Text='<%# Bind("Legajo") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="DNI">
            <EditItemTemplate>
                <asp:Label ID="lblEditDni" runat="server" Text='<%# Bind("DNI") %>'></asp:Label>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="Label2" runat="server" Text='<%# Bind("DNI") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
    </Columns>
</asp:GridView>

</div>
</asp:Content>