<%@ Page Title="BMLPaciente" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="BMLPaciente.aspx.cs" Inherits="TPI_GRUPO_25.BMLPaciente" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <!-- Acá pueden ir Scripts-->
    <style>
            body {
            background-color: #ffe5b4;
            margin: 0;
            padding: 0;
            }

        .navbar {
            background-color: #653208 !important;
        }

        .navbar .nav-link,
        .navbar .navbar-brand {
            color: #fce7c6;
            font-weight: 400;
        }
    </style>

</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="bg-naranja-suave w-100">
               <nav class="navbar navbar-expand-xl" CssClass="navbar" style="background-color: #653208;">
  <div class="container-fluid" >
    <a class="navbar-brand" href="SesionIniciadaAdministrador.aspx">Clínica TUP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDark" aria-controls="navbarDark" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse show" id="navbarDark">
      <ul class="navbar-nav me-auto mb-2 mb-xl-0 d-flex w-100">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="AltaMedico.aspx">Alta Médico</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="BMLMedico.aspx">BML Médico</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="AltaPaciente.aspx">Alta Paciente</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="InformesAdministrador.aspx">Informes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="TurnosAdministrador.aspx">Turnos</a>
        </li>
            <li class="nav-item ms-auto">
              <asp:Label class="nav-link mb-15" ID="usuarioAd" runat="server" Text="Usuario: Admin"></asp:Label>
            </li>
        <li class="nav-item">
<a class="nav-link btn btn-primary"  href="InicioSesion.aspx">Cerrar Sesión</a>

        </li>
      </ul>
    </div>
  </div>
</nav>
    </div>
     <asp:Label runat="server" ID="lblBienvenida" Text="¡Bienvenido Administrador! Estos son los pacientes de la clínica TUP." CssClass="h2 text-center d-block mt-5 mb-3 text-dark"></asp:Label>
        <br />
        &nbsp;&nbsp;
        <br />
        <br />
   <div class="container mt-5 pt-5">
    <asp:GridView ID="gvPacientes" runat="server"  DataKeyNames="ID_Paciente" AutoGenerateColumns="False" AllowPaging="True" CssClass="grid-style" Width="94%" HorizontalAlign="Center" CellPadding="3" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellSpacing="2" AutoGenerateDeleteButton="True" OnRowDeleting="gvPaciente_RowDeleting" AutoGenerateEditButton="True" OnRowCancelingEdit="gvPaciente_RowCancelingEdit" OnRowEditing="gvPaciente_RowEditing" OnRowUpdating="gvPaciente_RowUpdating" >
    <Columns>
        <asp:TemplateField HeaderText="DNI">
            <EditItemTemplate>
                <asp:Label ID="lblEditDniPaciente" runat="server" Text='<%# Bind("DNI") %>'></asp:Label>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="lblItDNI" runat="server" Text='<%# Bind("DNI") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Nombre">
            <EditItemTemplate>
                <asp:TextBox ID="txtEditTempNombre" runat="server"></asp:TextBox>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="lblItNombre" runat="server" Text='<%# Bind("Nombre") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Correo Electrónico">
            <EditItemTemplate>
                <asp:TextBox ID="txtEditCorreo" runat="server"></asp:TextBox>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="lblItCorreo" runat="server" Text='<%# Bind("Email") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="ID Turno">
            <ItemTemplate>
                <asp:Label ID="lblItIdTurno" runat="server" Text='<%# Bind("ID_Turno") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="ID Paciente">
            <ItemTemplate>
                <asp:Label ID="lblItIdPaciente" runat="server" Text='<%# Bind("ID_Paciente") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
    </Columns>
    <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
    <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />

    <PagerStyle HorizontalAlign="Center" CssClass="gv-pager" ForeColor="#8C4510"></PagerStyle>
      <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
      <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
      <SortedAscendingCellStyle BackColor="#FFF1D4" />
      <SortedAscendingHeaderStyle BackColor="#B95C30" />
      <SortedDescendingCellStyle BackColor="#F1E5CE" />
      <SortedDescendingHeaderStyle BackColor="#93451F" />

    </asp:GridView>

   </div>

    
     
    
</asp:Content>