<%@ Page Title="TurnosMedico" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="TurnosMedico.aspx.cs" Inherits="TPI_GRUPO_25.TurnosMedico" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
    body {
        background-color: #ffe5b4;
        margin: 0;
        padding: 0;
    }

    .navbar {
        background-color: #653208 !important;
    }

    .navbar .nav-link,
    .navbar .navbar-brand {
        color: #fce7c6;
        font-weight: 400;
    }
    .boton-personalizado {
    background-color: #BF7D56;
    color: black;            
    border: 1px solid black; 
    font-weight: bold;
}

.boton-personalizado:hover {
    background-color: #4d2606;
    color: white;           
    border: 1px solid black; 
}

.divFiltrar {
    border: 1px solid black;
    background-color: #FFC27D;
}

</style>
</asp:Content>

    <asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <div>
        <nav class="navbar navbar-expand-xl" CssClass="navbar" style="background-color: #653208;">
  <div class="container-fluid" >
    <a class="navbar-brand">Clínica TUP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDark" aria-controls="navbarDark" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse show" id="navbarDark">
      <ul class="navbar-nav me-auto mb-2 mb-xl-0 d-flex w-100">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#">Turnos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pacientes</a>
        </li>
            <li class="nav-item ms-auto">
              <asp:Label class="nav-link mb-15" ID="usuarioAd" runat="server" Text="Usuario: Médico"></asp:Label>
            </li>
        <li class="nav-item">
         <a class="nav-link" href="#">Cerrar sesion</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
        </div>
        <div class="px-4">
            <h2 class="my-4 text-center">¡Bienvenido a la Clínica TUP {Médico}, Estos son los Turnos!</h2>
            <div class="d-flex justify-content-center">
            <asp:Label CssClass="d-flex align-items-center h5" runat="server" Text="Buscar:"></asp:Label>
            <asp:TextBox runat="server" ID="txtBuscar" CssClass="form-control w-25 mx-2" />
            <asp:Button runat="server" ID="btnFiltrarTurnos" Text="Filtrar" CssClass="btn boton-personalizado " />
            </div>
            <div class="d-flex justify-content-center align-items-center py-4">
            <div class="divFiltrar px-2 col-sm-2">
                <asp:Label CssClass="h4" runat="server" Text="Filtrar por:"></asp:Label>
                <div class="divEspecialidad py-4">
                <asp:Label CssClass="h4" runat="server" Text="Especialidad:"></asp:Label>
                <div>
                <asp:CheckBox runat="server"/>
                <asp:Label CssClass="" runat="server" Text="Cardiología"></asp:Label>
                </div>
                <div>
                <asp:CheckBox runat="server"/>
                <asp:Label runat="server" Text="Pedriatría"></asp:Label>
                </div>
                </div>
            <div>
                <asp:Label CssClass="h4" runat="server" Text="Turno:"></asp:Label>
                <div class="">
                <asp:CheckBox runat="server"/>
                <asp:Label CssClass="" runat="server" Text="Mañana"></asp:Label>
                </div>
                <div>
                <asp:CheckBox runat="server"/>
                <asp:Label runat="server" Text="Tarde"></asp:Label>
                </div>
            </div>
            </div>
  <div class="w-100 px-4">
  <asp:GridView ID="gvTurnos" runat="server" AutoGenerateColumns="False" AllowPaging="True" CssClass="grid-style" Width="100%" HorizontalAlign="Center" CellPadding="3" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="Groove" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
  <Columns>
      <asp:BoundField HeaderText="Turno" DataField="DNI" />
      <asp:BoundField HeaderText="Paciente" DataField="Nombre" />
      <asp:BoundField HeaderText="Estado" DataField="Apellido" />
      <asp:BoundField HeaderText="Observación" DataField="FechaNacimiento" />
  </Columns>
  <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
  <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />

  <PagerStyle HorizontalAlign="Center" CssClass="gv-pager" ForeColor="#8C4510"></PagerStyle>
    <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
    <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
    <SortedAscendingCellStyle BackColor="#FFF1D4" />
    <SortedAscendingHeaderStyle BackColor="#B95C30" />
    <SortedDescendingCellStyle BackColor="#F1E5CE" />
    <SortedDescendingHeaderStyle BackColor="#93451F" />

  </asp:GridView>
 </div>
</div>
</div>
</asp:Content>
